const express = require('express');
const cors = require('cors');
const multer = require('multer');
const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');
const db = require('./src/db/database');

const app = express();
const PORT = process.env.PORT || 5000;

// Middleware
app.use(cors());
app.use(express.json());
app.use(
  "/uploads",
  express.static(path.join(__dirname, "uploads"))
);


// -------------------- MULTER SETUP --------------------
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    const uploadDir = path.join(__dirname, 'uploads');
    if (!fs.existsSync(uploadDir)) {
      fs.mkdirSync(uploadDir, { recursive: true });
    }
    cb(null, uploadDir);
  },
  filename: (req, file, cb) => {
    cb(null, `${Date.now()}-${file.originalname}`);
  }
});

const upload = multer({
  storage,
  limits: { fileSize: 50 * 1024 * 1024 },
  fileFilter: (req, file, cb) => {
  const allowedMimeTypes = [
  "audio/wav",
  "audio/x-wav",

  "audio/mpeg",
  "audio/mp3",

  "audio/mp4",
  "audio/x-m4a",   // ← THIS IS THE ONE BREAKING YOU
  "audio/m4a",

  "audio/webm",
  "audio/ogg",
]

  const allowedExtensions = /\.(wav|mp3|ogg|flac|webm)$/i

  const mimeOk = allowedMimeTypes.includes(file.mimetype)
  const extOk = allowedExtensions.test(file.originalname)

  if (mimeOk || extOk) {
    cb(null, true)
  } else {
    console.error("Rejected file:", file.mimetype, file.originalname)
    cb(new Error("Invalid audio format"))
  }
}

});

// -------------------- HEALTH --------------------
app.get('/health', (req, res) => {
  res.json({ status: 'ok' });
});

// -------------------- UPLOAD --------------------
app.post("/api/audio/upload", upload.single("audio"), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: "No file received" })
  }

  res.json({
    trackId: Date.now().toString(),
    originalFilename: req.file.originalname,
    durationSec: 0
  })
})


// -------------------- ANALYZE --------------------
app.post('/api/audio/analyze', (req, res) => {
  const { filePath } = req.body;

  if (!filePath) {
    return res.status(400).json({
      success: false,
      error: 'filePath is required'
    });
  }

  console.log('Analyzing audio file:', filePath);

  const pythonScriptPath = path.join(
    __dirname,
    '../ml-service/analyze_with_chords.py'
  );

  const pythonProcess = spawn('python3', [
    pythonScriptPath,
    filePath
  ]);
   pythonProcess.stdout.on('data', (data) => {
      process.stdout.write(data.toString());
    });
  let errorData = '';

  pythonProcess.stderr.on('data', (data) => {
    errorData += data.toString();
  });

  pythonProcess.on('close', (code) => {
    if (code !== 0) {
      console.error('Python error:', errorData);

      if (errorData.includes("KeyError: 'Unknown'")) {
        return res.status(400).json({
          success: false,
          error: 'Could not detect musical key',
          message: 'Please try a clearer melody or different audio input.'
        });
      }

      return res.status(500).json({
        success: false,
        error: 'Python analysis failed'
      });
    }

    // ✅ READ JSON FILE GENERATED BY PYTHON
    const analysisFilePath = path.join(
  __dirname,
  path.basename(filePath).replace(
    /\.(wav|mp3|ogg|flac)$/i,
    '_analysis.json'
  )
);


    console.log('✅ USING FILE-BASED ANALYSIS PATH');
   


    if (!fs.existsSync(analysisFilePath)) {
      return res.status(500).json({
        success: false,
        error: 'Analysis file not generated by Python'
      });
    }

    try {
      const fileContents = fs.readFileSync(analysisFilePath, 'utf-8');
      const analysisJson = JSON.parse(fileContents);
        db.run(
        `
        INSERT INTO analyses (original_filename, file_path, analysis_json)
        VALUES (?, ?, ?)
        `,
        [
          path.basename(filePath),
          filePath,
          JSON.stringify(analysisJson)
        ],
        function (err) {
          if (err) {
            console.error('❌ Failed to save analysis:', err.message);
          } else {
            console.log('✅ Analysis saved to DB with ID:', this.lastID);
          }
        }
    );

      return res.json(analysisJson);



    } catch (err) {
      return res.status(500).json({
        success: false,
        error: 'Failed to read analysis JSON'
      });
    }
  });
});
// -------------------- HISTORY --------------------

app.get('/api/audio/history', (req, res) => {
  db.all(
    `
    SELECT id, original_filename, created_at
    FROM analyses
    ORDER BY created_at DESC
    `,
    [],
    (err, rows) => {
      if (err) {
        console.error('❌ Failed to fetch history:', err.message);
        return res.status(500).json({
          success: false,
          error: 'Failed to fetch analysis history'
        });
      }

      res.json({
        success: true,
        history: rows
      });
    }
  );
});
// -------------------- HIST/ANALYSIS --------------------

app.get('/api/audio/analysis/:id', (req, res) => {
  const { id } = req.params;

  db.get(
    `
    SELECT analysis_json
    FROM analyses
    WHERE id = ?
    `,
    [id],
    (err, row) => {
      if (err) {
        console.error('❌ DB error:', err.message);
        return res.status(500).json({
          success: false,
          error: 'Database error'
        });
      }

      if (!row) {
        return res.status(404).json({
          success: false,
          error: 'Analysis not found'
        });
      }

      try {
        const analysis = JSON.parse(row.analysis_json);

        res.json({
          success: true,
          analysis
        });
      } catch (parseErr) {
        console.error('❌ JSON parse error:', parseErr.message);
        res.status(500).json({
          success: false,
          error: 'Corrupted analysis data'
        });
      }
    }
  );
});
// -------------------- DELETE --------------------
app.delete('/api/audio/analysis/:id', (req, res) => {
  const { id } = req.params;

  db.run(
    `
    DELETE FROM analyses
    WHERE id = ?
    `,
    [id],
    function (err) {
      if (err) {
        console.error('❌ Failed to delete analysis:', err.message);
        return res.status(500).json({
          success: false,
          error: 'Failed to delete analysis'
        });
      }

      if (this.changes === 0) {
        return res.status(404).json({
          success: false,
          error: 'Analysis not found'
        });
      }

      res.json({
        success: true,
        deletedId: id
      });
    }
  );
});

// -------------------- START SERVER --------------------
app.listen(PORT, () => {
  console.log(`🚀 Beatify Backend API running on http://localhost:${PORT}`);
});
